# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60dca4a5ff47f663021692bf5003367a8ce31d5356fdb25ccf49e27c7b2551b222ad70eb90aaf89e65e72e738410d346b972f5e10d2ff17fcb144f47e222a000

test:
  secret_key_base: 262a1b6ae70c5080d529df585c940400bd4071336cb28257e89f8be06750287b32a5aee8daa9b711bd9c02b4af8e061309a176e8ea657146199b59854f67e738

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
